---
title: "Delineating the Genetic Component of Gene Expression in Major Depression"
author: "Lorenza Dall'Aglio, Cathryn Lewis and Oliver Pain"
output: 
  html_document:
    toc: true
    theme: united
---

Published [Biological Psychiatry 2020](https://www.biologicalpsychiatryjournal.com/article/S0006-3223(20)31915-6/fulltext)

***

Welcome!

This website provides details of a project inferring differential gene expression in Major Depression based on GWAS summary statistics and summary-level gene expression data, an approach called Transcriptome-wide Association Study (TWAS).

***

#### [Code and Results](MDD_TWAS.html)

*** 

#### Reference:

To cite this work, please use the following:

Dall’Aglio, L., Lewis, C. M., & Pain, O. (2020). Delineating the Genetic Component of Gene Expression in Major Depression. Biological Psychiatry. https://doi.org/10.1016/j.biopsych.2020.09.010

***

Please contact Oliver Pain (oliver.pain@kcl.ac.uk) to if you have any questions or comments.

***

#### Funding:

This work is funded by the MRC (MR/N015746/1), and the National Institute for Health Research (NIHR) Biomedical Research Centre at South London and Maudsley NHS Foundation Trust and King’s College London. The authors acknowledge use of the research computing facility at King’s College London, Rosalind (https://rosalind.kcl.ac.uk), which is delivered in partnership with the NIHR Maudsley BRC, and part-funded by capital equipment grants from the Maudsley Charity (award 980) and Guy’s & St. Thomas’ Charity (TR130505). The views expressed are those of the authors and not necessarily those of the NHS, the NIHR or the Department of Health and Social Care. 

***
